apiVersion: compute.mycloud.com/v1
kind: EC2Instance

metadata:
  name: myinstance
  namespace: default

spec:
  amiID: "ami-02dfbd4ff395f2a1b"
  instanceType: "m3.medium"
  region: "us-east-1"
  keyPair: "my-test-key"
  subnet: "subnet-0fe6753e455be7796"
  securityGroups:
  - "sg-05d79d7df8c4f74f4"
  tags:
    environment: "test"
  
  storage:
    rootVolume:
      size: 10
      type: "gp2"
